[platformio]
default_envs = bridge_a

[env]
platform = espressif32@6.4.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_type = release
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
build_flags =
    -Os
    -D CORE_DEBUG_LEVEL=0
    -D BRIDGE_BAUDRATE=115200
    -D BRIDGE_HEARTBEAT_MS=1000
    -D BRIDGE_MAX_JSON_BYTES=200

[env:bridge_a]
extends = env
build_flags =
    ${env.build_flags}
    -D BRIDGE_ROLE_NAME=\"BRIDGE_A\"

[env:bridge_b]
extends = env
build_flags =
    ${env.build_flags}
    -D BRIDGE_ROLE_NAME=\"BRIDGE_B\"
